apiVersion: v1
kind: Service
metadata:
  name: santander
  namespace: santander
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: santander
